AcademyNet/Controllers/Admin/CourseController.cs
using BusinessLogicLayer;
using Microsoft.AspNetCore.Mvc;
using Course = Business_Entity.Course;

namespace AcademyNet.Controllers.Admin
{
    public class CourseController : Controller
    {
        private IWebHostEnvironment webHostEnvironment;
        public CourseController(IWebHostEnvironment _webHostEnvironment)
        {
            webHostEnvironment = _webHostEnvironment;
        }
        public IActionResult Index()
        {
            BLLHuman bLLHuman = new BLLHuman();
            ViewBag.BLLHuman = bLLHuman.GetAllRecords();
            return View();
        }

        //public IActionResult GetAllRecords()
        //{
        //    BLLCourse bLLCourse = new BLLCourse();
        //    ViewBag.BLLCourse = bLLCourse.GetAllRecords();
        //    return View();
        //}


        //ریختن دیتا مدل در مدل ویو
        public IActionResult Edit(int id)
        {
            BLLCourse bLLCourse = new BLLCourse();
            var bECourse = bLLCourse.SearchById(id);

            BLLHuman bLLHuman = new BLLHuman();
            ViewBag.teachers = bLLHuman.GetAllRecords();

            var modelCourse = new Models.Course
            {
                Title = bECourse.Title,
                Price = bECourse.Price,
                Descript = bECourse.Descript,
                TotalTime = bECourse.TotalTime,
                VideoUrl = bECourse.VideoIntro,
                ID = bECourse.ID,
                teachers = bECourse.TeacherCourses.Select(s => s.Teacher.Id).ToList()

            };

            return View(modelCourse);
        }
        //ریختن مدل ویو در دیتا مدل
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Models.Course course)
        {
            BLLCourse bLLCourse = new BLLCourse();
            var bECourse = bLLCourse.SearchById(course.ID);
            bECourse.ID = course.ID;
            bECourse.Title = course.Title;
            bECourse.Price = course.Price;
            bECourse.Descript = course.Descript;
            bECourse.TotalTime = course.TotalTime;

            if (course.VideoIntro != null)
            {
                UploadFile uploadFile = new UploadFile(webHostEnvironment);
                bECourse.VideoIntro = uploadFile.UploadVideo(course.VideoIntro);
            }
            bLLCourse.Update(bECourse);
            //چرا از redirect استفاده شد؟
            return RedirectToAction(nameof(ShowAllCourse));
        }

        public IActionResult Create()
        {
            return View("Create");
        }
        //جزئیات دوره
        public IActionResult Details(int courseID)
        {
            BLLCourse bLLCourse = new BLLCourse();
            Course course = new Course();
            course = bLLCourse.SearchById(courseID);

            return View(course);
        }
        public IActionResult ShowAllCourse()
        {
            BLLCourse bLLCourse = new BLLCourse();
            ViewBag.courses = bLLCourse.GetAllRecords();
            return View();
        }

        [HttpPost]
        public void Create(Models.Course course)
        {
            BLLCourse bLLCourse = new BLLCourse();
            Business_Entity.Course businessCourse = new Business_Entity.Course();
            businessCourse.Price = course.Price;
            businessCourse.Descript = course.Descript;
            businessCourse.ID = course.ID;
            businessCourse.TotalTime = course.TotalTime;
            businessCourse.Title = course.Title;
            UploadFile uploadFile = new UploadFile(webHostEnvironment);
            businessCourse.VideoIntro = uploadFile.UploadVideo(course.VideoIntro);

            bLLCourse.Create(businessCourse);

        }
        public void Update(Models.Course course)
        {
            BLLCourse bLLCourse = new BLLCourse();

            Business_Entity.Course businessCourse = new Business_Entity.Course();
            businessCourse.ID = course.ID;
            businessCourse.Price = course.Price;
            businessCourse.Descript = course.Descript;
            businessCourse.TotalTime = course.TotalTime;
            businessCourse.Title = course.Title;
            UploadFile uploadFile = new UploadFile(webHostEnvironment);
            businessCourse.VideoIntro = uploadFile.UploadVideo(course.VideoIntro);

            bLLCourse.Update(businessCourse);


        }
        public JsonResult HumanSearchJson()
        {
            return Json(new { redirect = "Search" });
        }
        public IActionResult Search(string search)
        {
            BLLCourse bLLCourse = new BLLCourse();
            List<Business_Entity.Course> courses = bLLCourse.Search(search);
            ViewBag.courses = courses;
            return View("ShowAllCourse", courses);
        }
        public IActionResult GetSkip(int skip)
        {
            BLLCourse bLLCourse = new BLLCourse();
            return View("ShowTeachersAccount", bLLCourse.GetSkip(skip));

        }

    }
}

AcademyNet/Controllers/Admin/HumanController.cs
using Microsoft.AspNetCore.Mvc;
using Business_Entity;
using BusinessLogicLayer;
using Microsoft.AspNetCore.Hosting;
using Newtonsoft.Json.Linq;

namespace AcademyNet.Controllers.Admin
{
    public class HumanController : Controller
    {
        private IWebHostEnvironment webHostEnvironment;
        public HumanController(IWebHostEnvironment _webHostEnvironment)
        {
            webHostEnvironment = _webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View("Create");
        }
        public IActionResult ShowAllTeachersAccount()
        {
            BLLHuman bLLHuman = new BLLHuman();

            return View("ShowTeachersAccount",bLLHuman.GetSkip(0));
        }
        [HttpPost]
        public void Create(Models.Human human)
        {
            BLLHuman bLLHuman = new BLLHuman();

            Business_Entity.Human businessHuman = new Human();
            businessHuman.Name = human.Name;
            businessHuman.Family = human.Family;
            businessHuman.Email = human.Email;
            businessHuman.gender = (Human.Gender)human.gender;
            businessHuman.Password = human.Password;
            businessHuman.role = (Human.Role)human.role;
            UploadFile uploadFile = new UploadFile(webHostEnvironment);
            if (human.Picture != null)
            {
                businessHuman.Picture = uploadFile.Upload(human.Picture);
            }
            bLLHuman.Create(businessHuman);

        }
        public void Update(Models.Human human)
        {
            BLLHuman bLLHuman = new BLLHuman();

            Business_Entity.Human businessHuman = new Human();
            businessHuman.Id = human.Id;
            businessHuman.Name = human.Name;
            businessHuman.Family = human.Family;
            businessHuman.Email = human.Email;
            businessHuman.gender = (Human.Gender)human.gender;
            businessHuman.Password = human.Password;
            businessHuman.role = (Human.Role)human.role;
            UploadFile uploadFile = new UploadFile(webHostEnvironment);
            if (human.Picture != null)
            {
                businessHuman.Picture = uploadFile.Upload(human.Picture);
            }
            bLLHuman.Update(businessHuman);

        }
        public JsonResult HumanSearchJson()
        {
            return Json(new { redirect = "Search" });
        }
        public IActionResult Search(string tags)
        {
            JArray jsonArray= new JArray(tags);
            dynamic data = JArray.Parse(jsonArray[0].ToString());
            List<string> split = new List<string>();
            foreach (dynamic item in data)
            {
                split.Add(item.tag.ToString()); 

            }
            BLLHuman bLLHuman= new BLLHuman();
            List<Human> humans = bLLHuman.Search(split);
            return View("ShowTeachersAccount", humans);
        }
        public IActionResult GetSkip(int skip)
        {
            BLLHuman bLLHuman = new BLLHuman();
            return View("ShowTeachersAccount", bLLHuman.GetSkip(skip));

        }
    }
}

AcademyNet/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AcademyNet.Controllers
{
    // [Authorize]
    public class ProfileController : Controller
    {
        //مقدار را از بسکت می گیرد و اکتیو می کند مقدار سبد خرید در این ویو را اکتیو می کند و آن قسمت ریز می شود
        public IActionResult Index(string showBasket, string message = null)
        {
           
            if (!string.IsNullOrWhiteSpace(message))
            {
                ViewBag.SuccessPayment = message;
            }
            else ViewBag.showBasket = "active";
            return View();
        }
    }
}

AcademyNet/Views/Shared/_Layout.cshtml
@using Business_Entity;
@using Microsoft.AspNetCore.Identity;
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json;
@using BusinessLogicLayer;
@inject IHttpContextAccessor httpContextAccessor
@inject UserManager<UserApp> userManager




<!DOCTYPE html>
<html lang="en">
<head>
    <!----- /*
          فایل رو اد کنیم  www.root  زیر وجود نداره برای همین باید به  css  چون آدرس های
    */ ----->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>قالب آموزش آنلاین ایزی لرن</title>
    <link rel="stylesheet" href="~/css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/bootstrap/bootstrap-rtl.css">
    <link rel="stylesheet" href="~/css/customcss/style.css">
    <link rel="stylesheet" href="~/css/fontawesome/css/all.css">
</head>
<body>
    <!----- Start header ----->
    <header class="bg-white">
        <div class="container">
            <div class="row pb-3">

                <div class="d-none d-lg-block col-lg-2">
                    <img src="~/images/logo/Knowledge" alt="EasyLearn" title="EasyLearn" class="img-fluid">
                </div>

                <div class="d-none d-lg-flex col-lg-6 align-items-center search-box">
                    <form action="" method="">
                        <div class="input-group">
                            <input type="search" name="" class="form-control rounded-pill" placeholder="عنوان مورد نظر خود را جستجو کنید ...">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-info rounded-pill font-13">جستجو</button>
                            </div>
                        </div>
                    </form>
                </div>
                <a href="#" class="border-left ml-3 dropdown" data-toggle="dropdown">
                    @{
                        var courseIDs = new List<int>();
                        if(httpContextAccessor.HttpContext.Session.GetString("basket") != null)
                        {
                            courseIDs = JsonConvert.DeserializeObject<List<int>>(httpContextAccessor.HttpContext.Session.GetString("basket"));
                        }
                        var bllCourse = new BLLCourse();
                        var courses = bllCourse.SearchById(courseIDs);
                    }
                    @if(courses.Count > 0)
                    {
                        <span class="badge badge-info badge-pill">@courses.Count</span><i class="fa fa-shopping-basket ml-3"></i>
                    }
                    <div class="dropdown-menu  dropdown-cart mt-3 mx-5">
                        <ul class="list-unstyled">
                            @foreach (var course in courses)
                            {
                                <li>
                                    <img width="50" height="50" src="~/images/bootstrap.jpg" class="m-1 ml-3">
                                    <div class="float-right">
                                        <small class=" mt-3 mr-2 d-block">@course.Title  (@course.Price تومان)</small>
                                    </div>
                                </li>
                            }
                          
                            <li>
                                <a asp-action="Index" asp-controller="Profile" asp-route-showBasket="active" button class="btn btn-info m-1 ml-3 font-12">پرداخت</button></a>
                                <div class="float-right">
                                    <small class=" mt-3 mr-2 d-block">قیمت کل : @courses.Sum(s=>s.Price)</small>
                                </div>
                            </li>
                        </ul>
                    </div>
                </a>

                <div class="d-none d-lg-flex col-lg-4 align-items-center justify-content-end">


                    @if (User.Identity.IsAuthenticated)
                    {
                        var user = await userManager.FindByNameAsync(User.Identity.Name);
                        <div>@user.FirstName @user.LastName</div>
                        <a asp-action="Logout" asp-controller="Account" class="btn btn-outline-info font-13 vazir-med-fa"><i class="fa fa-user-plus pl-1"></i>خروج</a>
                    }
                    else
                    {
                        <a asp-action="Register" asp-controller="Account" class="btn btn-outline-info font-13 vazir-med-fa"><i class="fa fa-user-plus pl-1"></i>ثبت نام</a>
                        <a asp-action="Login" asp-controller="Account" class="btn btn-info font-13 vazir-med-fa mx-2">ورود</a>
                    }


                </div>

            </div>

            <div class="row">
                <!----- Start mobile header ----->

                <div class="col-12 d-flex d-lg-none justify-content-center">
                    <img src="~/images/logo.jpg" alt="Easylearn" alt="Easylearn">
                </div>

                <div class="col-12 d-flex d-lg-none justify-content-center mb-4 mobile-header">
                    <a href="sign-up.html" class="border-left ml-3"><i class="fa fa-user-plus ml-3"></i></a>
                    <a href="login.html" class="border-left ml-3"><i class="fa fa-lock ml-3"></i></a>
                    <a href="teach.html" class="border-left ml-3"><i class="fa fa-graduation-cap ml-3"></i></a>
                    <a href="#" class="border-left ml-3 dropdown" data-toggle="dropdown">
                        <span class="badge badge-info badge-pill">2</span><i class="fa fa-shopping-basket ml-3"></i>

                    </a>
                    <a href="#search" data-toggle="collapse"><i class="fa fa-search"></i></a>
                </div>

                <div id="search" class=" d-lg-none col-10 mx-auto collapse mb-4 justify-content-center">
                    <form action="" method="">
                        <div class="input-group">
                            <input type="search" name="" class="form-control rounded-pill" placeholder="عنوان مورد نظر خود را جستجو کنید ...">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-info rounded-pill font-13">جستجو</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div><!----- End mobile header ----->
        </div>
    </header>
    <!----- End header ----->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-white">
        <!----- Start footer ----->
        <div class="container py-2">
            <div class="row">

                <div class="col-md-4">
                    <img src="~/images/logo4.jpg" alt="" class="img-fluid">
                    <p class="text-justify font-14 vazir mb-4">
                        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با
                        استفاده از طراحان گرافیک است.
                        چاپگرها و متون بلکه روزنامه و مجله در ستون و سطر آنچنان که لازم است.
                    </p>
                    <p class="font-14"><i class="fas fa-map-marker-alt text-muted ml-2"></i> ایران , تهران , زعفرانیه , ساختمان مهر</p>
                    <p class="font-14"><i class="fas fa-envelope text-muted ml-2"></i> info@sitename.com</p>
                    <p class="font-14"><i class="fa fa-phone text-muted ml-2"></i>021-12345678</p>
                </div>

                <div class="col-md-2 text-center footer-links">
                    <span class="mt-5 mb-3 d-block font-14">دسترسی سریع</span>
                    <ul class="list-unstyled">
                        <li class="my-3"><a href="#">درباره ما</a></li>
                        <li class="my-3"><a href="#">تماس با ما</a></li>
                        <li class="my-3"><a href="#">سوالات متداول</a></li>
                        <li class="my-3"><a href="#">تاریخچه سفارشات</a></li>
                    </ul>
                </div>

                <div class="col-md-2 text-center footer-links">
                    <span class="mt-5 mb-3 d-block font-14">لینک های مفید</span>
                    <ul class="list-unstyled">
                        <li class="my-3"><a href="#">حساب کاربری</a></li>
                        <li class="my-3"><a href="#">بازپرداخت</a></li>
                        <li class="my-3"><a href="#">تخفیف</a></li>
                        <li class="my-3"><a href="#">رهگیری سفارش</a></li>
                    </ul>
                </div>

                <div class="col-md-4 search-box text-center">
                    <h6 class="my-5">برای اطلاع از  تازه ترین ها به خبرنامه ما بپیوندید!</h6>
                    <form action="" method="">
                        <div class="input-group">
                            <input type="search" name="" class="form-control rounded-pill" placeholder="ایمیل خود را وارد کنید ...">
                            <div class="input-group-append">
                                <button type="submit" name="" class="btn btn-info rounded-pill font-13">اشتراک</button>
                            </div>
                        </div>
                    </form>
                    <div class="mt-5 social-media">
                        <a href="#"><i class="fab fa-instagram p-1" id="instagram"></i></a>
                        <a href="#"><i class="fab fa-twitter bg-info p-1"></i></a>
                        <a href="#"><i class="fab fa-youtube bg-danger p-1"></i></a>
                        <a href="#"><i class="fab fa-telegram bg-primary p-1"></i></a>
                    </div>
                </div>

            </div>


            <div class="row justify-content-end">
                <a class="topbutton"> <i class="fa fa-chevron-circle-up"> </i> </a>
            </div>


            <div class="row">
                <div class="col-12 text-center">
                    <hr>
                    <p class="text-muted font-14">© 1399 کلیه حقوق این سایت متعلق به ایزی لرن است</p>
                </div>
            </div>

        </div>
    </footer><!----- End footer ----->
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/myscript.js"></script>
    @await RenderSectionAsync("scripts", required: false)
</body>
</html>

AcademyNet/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google.">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template, eCommerce dashboard, analytic dashboard">
    <meta name="author" content="ThemeSelect">
    <title>متریالایز | الگوی منوی تاریک عمودی | مدرن </title>
    <link rel="apple-touch-icon" href="~/images/favicon/apple-touch-icon-152x152.png">
    <link rel="shortcut icon" type="~/image/x-icon" href="~/images/favicon/favicon-32x32.png">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- BEGIN: VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="~/vendors/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/animate-css/animate.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/chartist-js/chartist.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/chartist-js/chartist-plugin-tooltip.css">
    <!-- END: VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="~/css-rtl/style-rtl.min.css">
    <!-- BEGIN: Page Level CSS-->                ~/
    <link rel="stylesheet" type="text/css" href="~/css-rtl/themes/vertical-dark-menu-template/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="~/css-rtl/themes/vertical-dark-menu-template/style.min.css">
    <link rel="stylesheet" type="text/css" href="~/css-rtl/pages/dashboard-modern.css">
    <link rel="stylesheet" type="text/css" href="~/css-rtl/pages/intro.min.css">
    <!-- END: Page Level CSS-->
    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="~/css-rtl/custom/custom.css">
    @await RenderSectionAsync("pre", required: false)
    <!-- END: Custom CSS-->
</head>
<body>
    <!-- BEGIN: Header-->
    <header class="page-topbar" id="header">
        <div class="navbar navbar-fixed">
            <nav class="navbar-main navbar-color nav-collapsible sideNav-lock navbar-light">
                <div class="nav-wrapper">
                    <div class="header-search-wrapper hide-on-med-and-down">
                        <i class="material-icons">search</i>
                        <input class="header-search-input z-depth-2 iransans" type="text" name="Search" placeholder="جست و جو..." data-search="template-list">
                        <ul class="search-list collection display-none"></ul>
                    </div>
                    <ul class="navbar-list right">
                        <li class="dropdown-language"><a class="waves-effect waves-block waves-light translation-button" href="#" data-target="translation-dropdown"><span class="flag-icon flag-icon-ir"></span></a></li>
                        <li class="hide-on-med-and-down"><a class="waves-effect waves-block waves-light toggle-fullscreen" href="javascript:void(0);"><i class="material-icons">settings_overscan</i></a></li>
                        <li class="hide-on-large-only search-input-wrapper"><a class="waves-effect waves-block waves-light search-button" href="javascript:void(0);"><i class="material-icons">search</i></a></li>
                        <li><a class="waves-effect waves-block waves-light notification-button" href="javascript:void(0);" data-target="notifications-dropdown"><i class="material-icons">notifications_none<small class="notification-badge">5</small></i></a></li>
                        <li><a class="waves-effect waves-block waves-light profile-button" href="javascript:void(0);" data-target="profile-dropdown"><span class="avatar-status avatar-online"><img src="~/images/avatar/avatar-7.png" alt="avatar"><i></i></span></a></li>
                        <li><a class="waves-effect waves-block waves-light sidenav-trigger" href="#" data-target="slide-out-right"><i class="material-icons">format_indent_increase</i></a></li>
                    </ul>
                    <!-- translation-button-->
                
                    <!-- notifications-dropdown-->
                    <ul class="dropdown-content" id="notifications-dropdown">
                        <li>
                            <h6>اطلاعیه<span class="new badge">5</span></h6>
                        </li>
                        <li class="divider"></li>
                        
                    </ul>
                    <!-- profile-dropdown-->
                    <ul class="dropdown-content" id="profile-dropdown">
                        <li><a class="grey-text text-darken-1" href="user-profile-page.html"><i class="material-icons">person_outline</i> مشخصات</a></li>
                        <li><a class="grey-text text-darken-1" href="app-chat.html"><i class="material-icons">chat_bubble_outline</i> چت</a></li>
                        <li><a class="grey-text text-darken-1" href="page-faq.html"><i class="material-icons">help_outline</i> راهنمایی</a></li>
                        <li class="divider"></li>
                        <li><a class="grey-text text-darken-1" href="user-lock-screen.html"><i class="material-icons">lock_outline</i> قفل کردن</a></li>
                        <li><a class="grey-text text-darken-1" href="user-login.html"><i class="material-icons">keyboard_tab</i> خروج</a></li>
                    </ul>
                </div>
                <nav class="display-none search-sm">
                    <div class="nav-wrapper">
                        <form id="navbarForm">
                            <div class="input-field search-input-sm">
                                <input class="search-box-sm" type="search" required="" id="search" placeholder="Explore Materialize" data-search="template-list">
                                <label class="label-icon" for="search"><i class="material-icons search-sm-icon">search</i></label><i class="material-icons search-sm-close">close</i>
                                <ul class="search-list collection search-list-sm display-none"></ul>
                            </div>
                        </form>
                    </div>
                </nav>
            </nav>
        </div>
    </header>
    <!-- END: Header-->
    <!-- BEGIN: SideNav-->
    <aside class="sidenav-main nav-expanded nav-lock nav-collapsible sidenav-dark sidenav-active-rounded">
        <div class="brand-sidebar">
            <h1 class="logo-wrapper">
                <a class="brand-logo darken-1" href="index-2.html">
                    <img class="hide-on-med-and-down " src="~/images/logo/materialize-logo.png" alt="materialize logo" /><img class="show-on-medium-and-down hide-on-med-and-up" src="~/images/logo/materialize-logo-color.png"
                                                                                                                              alt="materialize logo" /><span class="logo-text hide-on-med-and-down">متریالایز</span>
                </a><a class="navbar-toggler" href="#"><i class="material-icons">radio_button_checked</i></a>
            </h1>
        </div>
        <ul class="sidenav sidenav-collapsible leftside-navigation collapsible sidenav-fixed menu-shadow" id="slide-out" data-menu="menu-navigation" data-collapsible="accordion">


            <li class="navigation-header">
                <a class="navigation-header-text">صفحات</a><i class="navigation-header-icon material-icons">more_horiz</i>
            </li>
            <li class="bold">
                <a class="waves-effect waves-cyan " href="@Url.Action("Create","Human")"><i class="material-icons">person_add</i><span class="menu-title" data-i18n="Teacher">ثبت اطلاعات</span></a>
            </li>
            <li class="bold">
                <a class="waves-effect waves-cyan " href="@Url.Action("ShowAllTeachersAccount","Human")"><i class="material-icons">groups</i><span class="menu-title" data-i18n="Chat">لیست اساتید</span></a>
            </li>
            <li class="bold">
                <a class="waves-effect waves-cyan " href="@Url.Action("Index","Course")"><i class="material-icons">groups</i><span class="menu-title" data-i18n="Chat">ایجاد دوره </span></a>
            </li>
            <li class="bold">
            <a class="waves-effect waves-cyan " href="@Url.Action("ShowAllCourse","Course")"><i class="material-icons">groups</i><span class="menu-title" data-i18n="Chat">لیست دوره ها </span></a>
            </li>
          

    </aside>
    <!-- END: SideNav-->

    <div id="main">
        <div class="row">
            @RenderBody()
        </div>
    </div>

    <!-- BEGIN: Footer-->

    <footer class="page-footer footer footer-static footer-light navbar-border navbar-shadow">
        <div class="footer-copyright">
            <div class="container">
                <span>
                    &copy; 2020 <a href="http://ticktockteam.ir/" target="_blank">تیم تیک تاک</a>
                    تمامی حقوق محفوظ است.
                </span><span class="right hide-on-small-only">
                    فارسی سازی شده توسط <a href="http://ticktockteam.ir/">تیم تیک تاک</a>
                </span>
            </div>
        </div>
    </footer>

    <!-- END: Footer-->
    <!-- BEGIN VENDOR JS-->
    <script src="~/js/vendors.min.js"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="~/vendors/chartjs/chart.min.js"></script>
    <script src="~/vendors/chartist-js/chartist.min.js"></script>
    <script src="~/vendors/chartist-js/chartist-plugin-tooltip.js"></script>
    <script src="~/vendors/chartist-js/chartist-plugin-fill-donut.min.js"></script>
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN THEME  JS-->
    <script src="~/js/plugins.min.js"></script>
    <script src="~/js/search.min.js"></script>
    <script src="~/js-rtl/custom/custom-script-rtl.min.js"></script>
    <script src="~/js/scripts/customizer.min.js"></script>
    <!-- END THEME  JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    @RenderSection("Script",required:false);
    <!-- END PAGE LEVEL JS-->
</body>
</html>